services:
  - type: web
    name: enclosure-generator-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true