services:
  - type: web
    name: enclosure-generator-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHONPATH
        value: .
    autoDeploy: true
